---
- name: "Stop and disable dynflow-sidekiq@{{ worker_name }} service"
  service:
    name: dynflow-sidekiq@{{ worker_name }}
    state: stopped
    enabled: no

- name: "Remove configuration for worker {{ worker_name }}"
  file:
    path: "/etc/foreman/dynflow/{{ worker_name }}.yml"
    state: absent
