---
- name: "Configure worker \"{{ worker_name }}\""
  template:
    dest: "/etc/foreman/dynflow/{{ worker_name }}.yml"
    src: templates/worker.yml.j2
  notify: "configuration changed"

- name: "Start and enable dynflow-sidekiq@{{ worker_name }} service"
  service:
    name: dynflow-sidekiq@{{ worker_name }}
    state: started
    enabled: yes
