# This playbook sets up the orchestrator
# and a single worker with 20 threads

- hosts: all
  roles:
    - role: dynflow-worker
      vars:
        worker_name: orchestrator
        worker_concurrency: 1
        worker_queues:
          - dynflow_orchestrator

    - role: dynflow-worker
      vars:
        worker_name: worker
        worker_concurrency: 20
        worker_queues:
          - default
          - remote_execution
